name: 上传到七牛存储
on: push

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: Ubuntu-20.04
    steps:
    - name: 检索文件
      uses: actions/checkout@v2

    - name: 执行上传
      uses: beimengyeyu/up2qn-plus@master
      run: |
        wget https://devtools.qiniu.com/qshell-v2.9.0-linux-amd64.tar.gz?ref=developer.qiniu.com
        tar -xzvf qshell-v2.9.0-linux-amd64.tar.gz
        cd qshell-v2.9.0-linux-amd64
        chmod +x qshell
        ./qshell account  ${{ secrets.AK }} ${{ secrets.SK }}

