name: 上传到七牛存储
on: push

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: Ubuntu-20.04
    steps:
    - name: 检索文件
      uses: actions/checkout@v2

    - name: 执行上传
      run: |
        wget https://devtools.qiniu.com/qshell-v2.9.0-linux-amd64.tar.gz
        pwd
        ls
        echo "tar qshell tar gz file"
        tar -xzvf qshell-v2.9.0-linux-amd64.tar.gz
        ls
        echo "add execute permission to qshell"
        chmod +x ./qshell
        echo "add qiniu account"
        ./qshell account  ${{ secrets.AK }} ${{ secrets.SK }} ${{ secrets.ACCOUNT }}
        echo "generate upload config"
        echo "{\"src_dir\":\"./\",\"ignore_dir\":true,\"bucket\":\"huangkl1024-homepage\",\"skip_file_prefixes\":\"qshell,.git,.github\",\"overwrite\":true}" > upload.conf
        echo "upload config is"
        cat upload.conf
        echo "upload repos"
        ./qshell qupload upload.conf

